use_frameworks!

target 'MoESwiftSample' do
  platform :ios, '10.0'
  pod 'MoEngage-iOS-SDK', :path => '../../'
end

target 'NotificationService' do
  platform :ios, '10.0'
end

target 'PushTemplates' do
  platform :ios, '10.0'
end

