name: Publish pods to CocoaPods

on:
  workflow_dispatch:

jobs:
  release:
    name: Create release
    runs-on: macos-latest

    steps:
    - name: Checkout scripts
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
        path: scripts
        repository: moengage/sdk-automation-scripts

    - name: Setup dev environment
      uses: ./scripts/actions/ios-action-setup
      env:
        SDK_BOT_ACCESS_TOKEN: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}

    - name: Checkout release repository
      uses: actions/checkout@v4
      with:
        ref: master
        path: source

    - name: Publish to CocoaPods
      run: ${{ github.workspace }}/scripts/scripts/release/ios/pod_push.rb
      working-directory: source
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
